name: Dry Publish to Maven Central

on:
  pull_request:
    branches:
      - main

jobs:
  call-reusable-workflow:
    uses: ./.github/workflows/maven-publish-base.yml # Call reusable workflow
    with:
      dryRun: "true"